-- Display aliases preserve catalogue IDs, rating history and all reader policies.
-- The trigger remains private and accepts no caller-supplied club ID.
create or replace function private.seed_club_display_aliases()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  insert into public.club_aliases(club_id,alias)
  select new.id,labels.alias from (values
('Real Madrid CF','Real Madrid'),
('Real Madrid CF','Реал Мадрид'),
('Real Madrid','Real Madrid'),
('Real Madrid','Реал Мадрид'),
('Manchester City FC','Man City'),
('Manchester City FC','Ман Сити'),
('Manchester City FC','Манчестер Сити'),
('Man City','Man City'),
('Man City','Ман Сити'),
('Man City','Манчестер Сити'),
('FC Barcelona','Barcelona'),
('FC Barcelona','Барселона'),
('Barcelona','Barcelona'),
('Barcelona','Барселона'),
('Barça','Barcelona'),
('Barça','Барселона'),
('Club Atlético de Madrid','Atlético Madrid'),
('Club Atlético de Madrid','Атлетико'),
('Club Atlético de Madrid','Атлетико Мадрид'),
('Atlético Madrid','Atlético Madrid'),
('Atlético Madrid','Атлетико'),
('Atlético Madrid','Атлетико Мадрид'),
('Atleti','Atlético Madrid'),
('Atleti','Атлетико'),
('Atleti','Атлетико Мадрид'),
('Paris Saint-Germain FC','PSG'),
('Paris Saint-Germain FC','ПСЖ'),
('Paris Saint-Germain FC','Пари Сен-Жермен'),
('PSG','PSG'),
('PSG','ПСЖ'),
('PSG','Пари Сен-Жермен'),
('Brighton & Hove Albion FC','Brighton'),
('Brighton & Hove Albion FC','Брайтон'),
('Brighton & Hove Albion FC','Брайтон энд Хоув Альбион'),
('Brighton','Brighton'),
('Brighton','Брайтон'),
('Brighton','Брайтон энд Хоув Альбион'),
('Brighton Hove','Brighton'),
('Brighton Hove','Брайтон'),
('Brighton Hove','Брайтон энд Хоув Альбион'),
('Liverpool FC','Liverpool'),
('Liverpool FC','Ливерпуль'),
('Liverpool','Liverpool'),
('Liverpool','Ливерпуль'),
('Arsenal FC','Arsenal'),
('Arsenal FC','Арсенал'),
('Arsenal','Arsenal'),
('Arsenal','Арсенал'),
('Manchester United FC','Man United'),
('Manchester United FC','Ман Юнайтед'),
('Manchester United FC','Манчестер Юнайтед'),
('Man United','Man United'),
('Man United','Ман Юнайтед'),
('Man United','Манчестер Юнайтед'),
('Chelsea FC','Chelsea'),
('Chelsea FC','Челси'),
('Chelsea','Chelsea'),
('Chelsea','Челси'),
('Tottenham Hotspur FC','Tottenham'),
('Tottenham Hotspur FC','Тоттенхэм'),
('Tottenham','Tottenham'),
('Tottenham','Тоттенхэм'),
('Aston Villa FC','Aston Villa'),
('Aston Villa FC','Астон Вилла'),
('Aston Villa','Aston Villa'),
('Aston Villa','Астон Вилла'),
('West Ham United FC','West Ham'),
('West Ham United FC','Вест Хэм'),
('West Ham','West Ham'),
('West Ham','Вест Хэм'),
('Burnley FC','Burnley'),
('Burnley FC','Бернли'),
('Burnley','Burnley'),
('Burnley','Бернли'),
('Brentford FC','Brentford'),
('Brentford FC','Брентфорд'),
('Brentford','Brentford'),
('Brentford','Брентфорд'),
('AFC Bournemouth','Bournemouth'),
('AFC Bournemouth','Борнмут'),
('Bournemouth','Bournemouth'),
('Bournemouth','Борнмут'),
('Wolverhampton Wanderers FC','Wolves'),
('Wolverhampton Wanderers FC','Вулверхэмптон'),
('Wolves','Wolves'),
('Wolves','Вулверхэмптон'),
('Fulham FC','Fulham'),
('Fulham FC','Фулхэм'),
('Fulham','Fulham'),
('Fulham','Фулхэм'),
('Newcastle United FC','Newcastle'),
('Newcastle United FC','Ньюкасл'),
('Newcastle','Newcastle'),
('Newcastle','Ньюкасл'),
('Nottingham Forest FC','Nottingham Forest'),
('Nottingham Forest FC','Ноттингем Форест'),
('Nottingham Forest','Nottingham Forest'),
('Nottingham Forest','Ноттингем Форест'),
('Nottingham','Nottingham Forest'),
('Nottingham','Ноттингем Форест'),
('Sunderland AFC','Sunderland'),
('Sunderland AFC','Сандерленд'),
('Sunderland','Sunderland'),
('Sunderland','Сандерленд'),
('Leeds United FC','Leeds'),
('Leeds United FC','Лидс'),
('Leeds','Leeds'),
('Leeds','Лидс'),
('Leeds United','Leeds'),
('Leeds United','Лидс'),
('Everton FC','Everton'),
('Everton FC','Эвертон'),
('Everton','Everton'),
('Everton','Эвертон'),
('Crystal Palace FC','Crystal Palace'),
('Crystal Palace FC','Кристал Пэлас'),
('Crystal Palace','Crystal Palace'),
('Crystal Palace','Кристал Пэлас'),
('Coventry City FC','Coventry'),
('Coventry City FC','Ковентри'),
('Coventry','Coventry'),
('Coventry','Ковентри'),
('Coventry City','Coventry'),
('Coventry City','Ковентри'),
('Hull City AFC','Hull City'),
('Hull City AFC','Халл Сити'),
('Hull City','Hull City'),
('Hull City','Халл Сити'),
('Ipswich Town FC','Ipswich'),
('Ipswich Town FC','Ипсвич'),
('Ipswich','Ipswich'),
('Ipswich','Ипсвич'),
('Ipswich Town','Ipswich'),
('Ipswich Town','Ипсвич'),
('Athletic Club','Athletic Club'),
('Athletic Club','Атлетик'),
('Athletic Club','Атлетик Бильбао'),
('Athletic','Athletic Club'),
('Athletic','Атлетик'),
('Athletic','Атлетик Бильбао'),
('CA Osasuna','Osasuna'),
('CA Osasuna','Осасуна'),
('Osasuna','Osasuna'),
('Osasuna','Осасуна'),
('Deportivo Alavés','Alavés'),
('Deportivo Alavés','Алавес'),
('Alavés','Alavés'),
('Alavés','Алавес'),
('Elche CF','Elche'),
('Elche CF','Эльче'),
('Elche','Elche'),
('Elche','Эльче'),
('Getafe CF','Getafe'),
('Getafe CF','Хетафе'),
('Getafe','Getafe'),
('Getafe','Хетафе'),
('Girona FC','Girona'),
('Girona FC','Жирона'),
('Girona','Girona'),
('Girona','Жирона'),
('Levante UD','Levante'),
('Levante UD','Леванте'),
('Levante','Levante'),
('Levante','Леванте'),
('Rayo Vallecano de Madrid','Rayo Vallecano'),
('Rayo Vallecano de Madrid','Райо Вальекано'),
('Rayo Vallecano','Rayo Vallecano'),
('Rayo Vallecano','Райо Вальекано'),
('RC Celta de Vigo','Celta'),
('RC Celta de Vigo','Сельта'),
('Celta','Celta'),
('Celta','Сельта'),
('RCD Espanyol de Barcelona','Espanyol'),
('RCD Espanyol de Barcelona','Эспаньол'),
('Espanyol','Espanyol'),
('Espanyol','Эспаньол'),
('RCD Mallorca','Mallorca'),
('RCD Mallorca','Мальорка'),
('Mallorca','Mallorca'),
('Mallorca','Мальорка'),
('Real Betis Balompié','Real Betis'),
('Real Betis Balompié','Бетис'),
('Real Betis Balompié','Реал Бетис'),
('Real Betis','Real Betis'),
('Real Betis','Бетис'),
('Real Betis','Реал Бетис'),
('Real Sociedad de Fútbol','Real Sociedad'),
('Real Sociedad de Fútbol','Реал Сосьедад'),
('Real Sociedad','Real Sociedad'),
('Real Sociedad','Реал Сосьедад'),
('Real Oviedo','Real Oviedo'),
('Real Oviedo','Реал Овьедо'),
('Sevilla FC','Sevilla'),
('Sevilla FC','Севилья'),
('Sevilla','Sevilla'),
('Sevilla','Севилья'),
('Valencia CF','Valencia'),
('Valencia CF','Валенсия'),
('Valencia','Valencia'),
('Valencia','Валенсия'),
('Villarreal CF','Villarreal'),
('Villarreal CF','Вильярреал'),
('Villarreal','Villarreal'),
('Villarreal','Вильярреал'),
('Málaga CF','Málaga'),
('Málaga CF','Малага'),
('Málaga','Málaga'),
('Málaga','Малага'),
('RC Deportivo La Coruña','Deportivo'),
('RC Deportivo La Coruña','Депортиво'),
('RC Deportivo La Coruña','Депортиво Ла-Корунья'),
('Deportivo','Deportivo'),
('Deportivo','Депортиво'),
('Deportivo','Депортиво Ла-Корунья'),
('Real Racing Club de Santander','Racing Santander'),
('Real Racing Club de Santander','Расинг'),
('Real Racing Club de Santander','Расинг Сантандер'),
('Racing Santander','Racing Santander'),
('Racing Santander','Расинг'),
('Racing Santander','Расинг Сантандер'),
('Santander','Racing Santander'),
('Santander','Расинг'),
('Santander','Расинг Сантандер'),
('FC Bayern München','Bayern'),
('FC Bayern München','Бавария'),
('Bayern','Bayern'),
('Bayern','Бавария'),
('Borussia Dortmund','Dortmund'),
('Borussia Dortmund','Боруссия Д'),
('Borussia Dortmund','Боруссия Дортмунд'),
('Dortmund','Dortmund'),
('Dortmund','Боруссия Д'),
('Dortmund','Боруссия Дортмунд'),
('Borussia Mönchengladbach','Mönchengladbach'),
('Borussia Mönchengladbach','Боруссия М'),
('Borussia Mönchengladbach','Боруссия Мёнхенгладбах'),
('Mönchengladbach','Mönchengladbach'),
('Mönchengladbach','Боруссия М'),
('Mönchengladbach','Боруссия Мёнхенгладбах'),
('M''gladbach','Mönchengladbach'),
('M''gladbach','Боруссия М'),
('M''gladbach','Боруссия Мёнхенгладбах'),
('Bayer 04 Leverkusen','Leverkusen'),
('Bayer 04 Leverkusen','Байер'),
('Bayer 04 Leverkusen','Байер Леверкузен'),
('Leverkusen','Leverkusen'),
('Leverkusen','Байер'),
('Leverkusen','Байер Леверкузен'),
('RB Leipzig','RB Leipzig'),
('RB Leipzig','РБ Лейпциг'),
('Eintracht Frankfurt','Frankfurt'),
('Eintracht Frankfurt','Айнтрахт'),
('Eintracht Frankfurt','Айнтрахт Франкфурт'),
('Frankfurt','Frankfurt'),
('Frankfurt','Айнтрахт'),
('Frankfurt','Айнтрахт Франкфурт'),
('VfL Wolfsburg','Wolfsburg'),
('VfL Wolfsburg','Вольфсбург'),
('Wolfsburg','Wolfsburg'),
('Wolfsburg','Вольфсбург'),
('SV Werder Bremen','Werder Bremen'),
('SV Werder Bremen','Вердер'),
('Werder Bremen','Werder Bremen'),
('Werder Bremen','Вердер'),
('Bremen','Werder Bremen'),
('Bremen','Вердер'),
('VfB Stuttgart','Stuttgart'),
('VfB Stuttgart','Штутгарт'),
('Stuttgart','Stuttgart'),
('Stuttgart','Штутгарт'),
('TSG 1899 Hoffenheim','Hoffenheim'),
('TSG 1899 Hoffenheim','Хоффенхайм'),
('Hoffenheim','Hoffenheim'),
('Hoffenheim','Хоффенхайм'),
('1. FSV Mainz 05','Mainz'),
('1. FSV Mainz 05','Майнц'),
('Mainz','Mainz'),
('Mainz','Майнц'),
('1. FC Köln','Köln'),
('1. FC Köln','Кёльн'),
('Köln','Köln'),
('Köln','Кёльн'),
('1. FC Union Berlin','Union Berlin'),
('1. FC Union Berlin','Унион Берлин'),
('Union Berlin','Union Berlin'),
('Union Berlin','Унион Берлин'),
('1. FC Heidenheim 1846','Heidenheim'),
('1. FC Heidenheim 1846','Хайденхайм'),
('Heidenheim','Heidenheim'),
('Heidenheim','Хайденхайм'),
('SC Freiburg','Freiburg'),
('SC Freiburg','Фрайбург'),
('Freiburg','Freiburg'),
('Freiburg','Фрайбург'),
('FC Augsburg','Augsburg'),
('FC Augsburg','Аугсбург'),
('Augsburg','Augsburg'),
('Augsburg','Аугсбург'),
('Hamburger SV','Hamburg'),
('Hamburger SV','Гамбург'),
('Hamburg','Hamburg'),
('Hamburg','Гамбург'),
('HSV','Hamburg'),
('HSV','Гамбург'),
('FC St. Pauli 1910','St. Pauli'),
('FC St. Pauli 1910','Санкт-Паули'),
('St. Pauli','St. Pauli'),
('St. Pauli','Санкт-Паули'),
('FC Schalke 04','Schalke'),
('FC Schalke 04','Шальке'),
('Schalke','Schalke'),
('Schalke','Шальке'),
('SC Paderborn 07','Paderborn'),
('SC Paderborn 07','Падерборн'),
('Paderborn','Paderborn'),
('Paderborn','Падерборн'),
('SC Paderborn','Paderborn'),
('SC Paderborn','Падерборн'),
('SV 07 Elversberg','Elversberg'),
('SV 07 Elversberg','Эльверсберг'),
('Elversberg','Elversberg'),
('Elversberg','Эльверсберг'),
('AC Milan','AC Milan'),
('AC Milan','Милан'),
('Milan','AC Milan'),
('Milan','Милан'),
('FC Internazionale Milano','Inter'),
('FC Internazionale Milano','Интер'),
('Inter','Inter'),
('Inter','Интер'),
('Juventus FC','Juventus'),
('Juventus FC','Ювентус'),
('Juventus','Juventus'),
('Juventus','Ювентус'),
('SSC Napoli','Napoli'),
('SSC Napoli','Наполи'),
('Napoli','Napoli'),
('Napoli','Наполи'),
('Atalanta BC','Atalanta'),
('Atalanta BC','Аталанта'),
('Atalanta','Atalanta'),
('Atalanta','Аталанта'),
('Bologna FC 1909','Bologna'),
('Bologna FC 1909','Болонья'),
('Bologna','Bologna'),
('Bologna','Болонья'),
('AS Roma','Roma'),
('AS Roma','Рома'),
('Roma','Roma'),
('Roma','Рома'),
('SS Lazio','Lazio'),
('SS Lazio','Лацио'),
('Lazio','Lazio'),
('Lazio','Лацио'),
('ACF Fiorentina','Fiorentina'),
('ACF Fiorentina','Фиорентина'),
('Fiorentina','Fiorentina'),
('Fiorentina','Фиорентина'),
('Como 1907','Como'),
('Como 1907','Комо'),
('Como','Como'),
('Como','Комо'),
('Cagliari Calcio','Cagliari'),
('Cagliari Calcio','Кальяри'),
('Cagliari','Cagliari'),
('Cagliari','Кальяри'),
('Genoa CFC','Genoa'),
('Genoa CFC','Дженоа'),
('Genoa','Genoa'),
('Genoa','Дженоа'),
('Hellas Verona FC','Verona'),
('Hellas Verona FC','Верона'),
('Verona','Verona'),
('Verona','Верона'),
('Parma Calcio 1913','Parma'),
('Parma Calcio 1913','Парма'),
('Parma','Parma'),
('Parma','Парма'),
('Udinese Calcio','Udinese'),
('Udinese Calcio','Удинезе'),
('Udinese','Udinese'),
('Udinese','Удинезе'),
('Torino FC','Torino'),
('Torino FC','Торино'),
('Torino','Torino'),
('Torino','Торино'),
('US Sassuolo Calcio','Sassuolo'),
('US Sassuolo Calcio','Сассуоло'),
('Sassuolo','Sassuolo'),
('Sassuolo','Сассуоло'),
('US Lecce','Lecce'),
('US Lecce','Лечче'),
('Lecce','Lecce'),
('Lecce','Лечче'),
('US Cremonese','Cremonese'),
('US Cremonese','Кремонезе'),
('Cremonese','Cremonese'),
('Cremonese','Кремонезе'),
('AC Pisa 1909','Pisa'),
('AC Pisa 1909','Пиза'),
('Pisa','Pisa'),
('Pisa','Пиза'),
('Olympique de Marseille','Marseille'),
('Olympique de Marseille','Марсель'),
('Marseille','Marseille'),
('Marseille','Марсель'),
('Olympique Lyonnais','Lyon'),
('Olympique Lyonnais','Лион'),
('Lyon','Lyon'),
('Lyon','Лион'),
('Olympique Lyon','Lyon'),
('Olympique Lyon','Лион'),
('AS Monaco FC','Monaco'),
('AS Monaco FC','Монако'),
('Monaco','Monaco'),
('Monaco','Монако'),
('Lille OSC','Lille'),
('Lille OSC','Лилль'),
('Lille','Lille'),
('Lille','Лилль'),
('Racing Club de Lens','Lens'),
('Racing Club de Lens','Ланс'),
('Lens','Lens'),
('Lens','Ланс'),
('RC Lens','Lens'),
('RC Lens','Ланс'),
('OGC Nice','Nice'),
('OGC Nice','Ницца'),
('Nice','Nice'),
('Nice','Ницца'),
('Stade Rennais FC 1901','Rennes'),
('Stade Rennais FC 1901','Ренн'),
('Rennes','Rennes'),
('Rennes','Ренн'),
('Stade Rennais','Rennes'),
('Stade Rennais','Ренн'),
('Stade Brestois 29','Brest'),
('Stade Brestois 29','Брест'),
('Brest','Brest'),
('Brest','Брест'),
('RC Strasbourg Alsace','Strasbourg'),
('RC Strasbourg Alsace','Страсбур'),
('Strasbourg','Strasbourg'),
('Strasbourg','Страсбур'),
('Toulouse FC','Toulouse'),
('Toulouse FC','Тулуза'),
('Toulouse','Toulouse'),
('Toulouse','Тулуза'),
('Le Havre AC','Le Havre'),
('Le Havre AC','Гавр'),
('Le Havre','Le Havre'),
('Le Havre','Гавр'),
('FC Nantes','Nantes'),
('FC Nantes','Нант'),
('Nantes','Nantes'),
('Nantes','Нант'),
('AJ Auxerre','Auxerre'),
('AJ Auxerre','Осер'),
('Auxerre','Auxerre'),
('Auxerre','Осер'),
('Angers SCO','Angers'),
('Angers SCO','Анже'),
('Angers','Angers'),
('Angers','Анже'),
('FC Lorient','Lorient'),
('FC Lorient','Лорьян'),
('Lorient','Lorient'),
('Lorient','Лорьян'),
('FC Metz','Metz'),
('FC Metz','Мец'),
('Metz','Metz'),
('Metz','Мец'),
('Paris FC','Paris FC'),
('Paris FC','Париж'),
('ES Troyes AC','Troyes'),
('ES Troyes AC','Труа'),
('Troyes','Troyes'),
('Troyes','Труа'),
('Le Mans FC','Le Mans'),
('Le Mans FC','Ле-Ман'),
('Le Mans','Le Mans'),
('Le Mans','Ле-Ман'),
('AFC Ajax','Ajax'),
('AFC Ajax','Аякс'),
('Ajax','Ajax'),
('Ajax','Аякс'),
('PSV','PSV'),
('PSV','ПСВ'),
('Sport Lisboa e Benfica','Benfica'),
('Sport Lisboa e Benfica','Бенфика'),
('Benfica','Benfica'),
('Benfica','Бенфика'),
('Sporting Clube de Portugal','Sporting CP'),
('Sporting Clube de Portugal','Спортинг'),
('Sporting CP','Sporting CP'),
('Sporting CP','Спортинг'),
('Club Brugge KV','Club Brugge'),
('Club Brugge KV','Брюгге'),
('Club Brugge','Club Brugge'),
('Club Brugge','Брюгге'),
('Royale Union Saint-Gilloise','Union SG'),
('Royale Union Saint-Gilloise','Юнион'),
('Royale Union Saint-Gilloise','Юнион Сен-Жиллуаз'),
('Union SG','Union SG'),
('Union SG','Юнион'),
('Union SG','Юнион Сен-Жиллуаз'),
('FC København','Copenhagen'),
('FC København','Копенгаген'),
('Copenhagen','Copenhagen'),
('Copenhagen','Копенгаген'),
('FK Bodø/Glimt','Bodø/Glimt'),
('FK Bodø/Glimt','Будё-Глимт'),
('Bodø/Glimt','Bodø/Glimt'),
('Bodø/Glimt','Будё-Глимт'),
('FK Kairat','Kairat'),
('FK Kairat','Кайрат'),
('Kairat','Kairat'),
('Kairat','Кайрат'),
('Galatasaray SK','Galatasaray'),
('Galatasaray SK','Галатасарай'),
('Galatasaray','Galatasaray'),
('Galatasaray','Галатасарай'),
('PAE Olympiakos SFP','Olympiacos'),
('PAE Olympiakos SFP','Олимпиакос'),
('Olympiacos','Olympiacos'),
('Olympiacos','Олимпиакос'),
('Paphos FC','Paphos'),
('Paphos FC','Пафос'),
('Paphos','Paphos'),
('Paphos','Пафос'),
('Qarabağ Ağdam FK','Qarabağ'),
('Qarabağ Ağdam FK','Карабах'),
('Qarabağ','Qarabağ'),
('Qarabağ','Карабах'),
('SK Slavia Praha','Slavia Prague'),
('SK Slavia Praha','Славия'),
('SK Slavia Praha','Славия Прага'),
('Slavia Prague','Slavia Prague'),
('Slavia Prague','Славия'),
('Slavia Prague','Славия Прага'),
('Slavia Praha','Slavia Prague'),
('Slavia Praha','Славия'),
('Slavia Praha','Славия Прага'),
('AC Monza','Monza'),
('AC Monza','Монца'),
('Monza','Monza'),
('Monza','Монца'),
('FC Porto','Porto'),
('FC Porto','Порту'),
('Porto','Porto'),
('Porto','Порту'),
('Fenerbahçe SK','Fenerbahçe'),
('Fenerbahçe SK','Фенербахче'),
('Fenerbahçe','Fenerbahçe'),
('Fenerbahçe','Фенербахче'),
('Feyenoord Rotterdam','Feyenoord'),
('Feyenoord Rotterdam','Фейеноорд'),
('Feyenoord','Feyenoord'),
('Feyenoord','Фейеноорд'),
('FK Shakhtar Donetsk','Shakhtar'),
('FK Shakhtar Donetsk','Шахтёр'),
('FK Shakhtar Donetsk','Шахтёр Донецк'),
('Shakhtar','Shakhtar'),
('Shakhtar','Шахтёр'),
('Shakhtar','Шахтёр Донецк'),
('Shaktar','Shakhtar'),
('Shaktar','Шахтёр'),
('Shaktar','Шахтёр Донецк'),
('Frosinone Calcio','Frosinone'),
('Frosinone Calcio','Фрозиноне'),
('Frosinone','Frosinone'),
('Frosinone','Фрозиноне'),
('LASK Linz','LASK'),
('LASK Linz','ЛАСК'),
('LASK','LASK'),
('LASK','ЛАСК'),
('PAE AEK','AEK Athens'),
('PAE AEK','АЕК'),
('PAE AEK','АЕК Афины'),
('AEK Athens','AEK Athens'),
('AEK Athens','АЕК'),
('AEK Athens','АЕК Афины'),
('Sabah FK','Sabah'),
('Sabah FK','Сабах'),
('Sabah','Sabah'),
('Sabah','Сабах'),
('ŠK Slovan Bratislava','Slovan Bratislava'),
('ŠK Slovan Bratislava','Слован'),
('ŠK Slovan Bratislava','Слован Братислава'),
('Slovan Bratislava','Slovan Bratislava'),
('Slovan Bratislava','Слован'),
('Slovan Bratislava','Слован Братислава'),
('Sl. Bratislava','Slovan Bratislava'),
('Sl. Bratislava','Слован'),
('Sl. Bratislava','Слован Братислава'),
('Venezia FC','Venezia'),
('Venezia FC','Венеция'),
('Venezia','Venezia'),
('Venezia','Венеция'),
('Viking FK','Viking'),
('Viking FK','Викинг'),
('Viking','Viking'),
('Viking','Викинг'),
('Зенит','Zenit'),
('Зенит','Зенит'),
('Zenit','Zenit'),
('Zenit','Зенит'),
('Спартак','Spartak Moscow'),
('Спартак','Спартак'),
('Спартак','Спартак Москва'),
('Spartak Moscow','Spartak Moscow'),
('Spartak Moscow','Спартак'),
('Spartak Moscow','Спартак Москва'),
('Динамо Москва','Dynamo Moscow'),
('Динамо Москва','Динамо Москва'),
('Dynamo Moscow','Dynamo Moscow'),
('Dynamo Moscow','Динамо Москва'),
('Краснодар','Krasnodar'),
('Краснодар','Краснодар'),
('Krasnodar','Krasnodar'),
('Krasnodar','Краснодар')
  ) labels(source_name,alias)
  where lower(labels.source_name)=lower(new.name) or lower(labels.source_name)=lower(new.short_name)
  on conflict do nothing;
  return new;
end $$;
revoke all on function private.seed_club_display_aliases() from public,anon,authenticated;
create trigger seed_club_display_aliases after insert or update of name,short_name
  on public.clubs for each row execute function private.seed_club_display_aliases();
insert into public.club_aliases(club_id,alias)
select c.id,labels.alias from public.clubs c join (values
('Real Madrid CF','Real Madrid'),
('Real Madrid CF','Реал Мадрид'),
('Real Madrid','Real Madrid'),
('Real Madrid','Реал Мадрид'),
('Manchester City FC','Man City'),
('Manchester City FC','Ман Сити'),
('Manchester City FC','Манчестер Сити'),
('Man City','Man City'),
('Man City','Ман Сити'),
('Man City','Манчестер Сити'),
('FC Barcelona','Barcelona'),
('FC Barcelona','Барселона'),
('Barcelona','Barcelona'),
('Barcelona','Барселона'),
('Barça','Barcelona'),
('Barça','Барселона'),
('Club Atlético de Madrid','Atlético Madrid'),
('Club Atlético de Madrid','Атлетико'),
('Club Atlético de Madrid','Атлетико Мадрид'),
('Atlético Madrid','Atlético Madrid'),
('Atlético Madrid','Атлетико'),
('Atlético Madrid','Атлетико Мадрид'),
('Atleti','Atlético Madrid'),
('Atleti','Атлетико'),
('Atleti','Атлетико Мадрид'),
('Paris Saint-Germain FC','PSG'),
('Paris Saint-Germain FC','ПСЖ'),
('Paris Saint-Germain FC','Пари Сен-Жермен'),
('PSG','PSG'),
('PSG','ПСЖ'),
('PSG','Пари Сен-Жермен'),
('Brighton & Hove Albion FC','Brighton'),
('Brighton & Hove Albion FC','Брайтон'),
('Brighton & Hove Albion FC','Брайтон энд Хоув Альбион'),
('Brighton','Brighton'),
('Brighton','Брайтон'),
('Brighton','Брайтон энд Хоув Альбион'),
('Brighton Hove','Brighton'),
('Brighton Hove','Брайтон'),
('Brighton Hove','Брайтон энд Хоув Альбион'),
('Liverpool FC','Liverpool'),
('Liverpool FC','Ливерпуль'),
('Liverpool','Liverpool'),
('Liverpool','Ливерпуль'),
('Arsenal FC','Arsenal'),
('Arsenal FC','Арсенал'),
('Arsenal','Arsenal'),
('Arsenal','Арсенал'),
('Manchester United FC','Man United'),
('Manchester United FC','Ман Юнайтед'),
('Manchester United FC','Манчестер Юнайтед'),
('Man United','Man United'),
('Man United','Ман Юнайтед'),
('Man United','Манчестер Юнайтед'),
('Chelsea FC','Chelsea'),
('Chelsea FC','Челси'),
('Chelsea','Chelsea'),
('Chelsea','Челси'),
('Tottenham Hotspur FC','Tottenham'),
('Tottenham Hotspur FC','Тоттенхэм'),
('Tottenham','Tottenham'),
('Tottenham','Тоттенхэм'),
('Aston Villa FC','Aston Villa'),
('Aston Villa FC','Астон Вилла'),
('Aston Villa','Aston Villa'),
('Aston Villa','Астон Вилла'),
('West Ham United FC','West Ham'),
('West Ham United FC','Вест Хэм'),
('West Ham','West Ham'),
('West Ham','Вест Хэм'),
('Burnley FC','Burnley'),
('Burnley FC','Бернли'),
('Burnley','Burnley'),
('Burnley','Бернли'),
('Brentford FC','Brentford'),
('Brentford FC','Брентфорд'),
('Brentford','Brentford'),
('Brentford','Брентфорд'),
('AFC Bournemouth','Bournemouth'),
('AFC Bournemouth','Борнмут'),
('Bournemouth','Bournemouth'),
('Bournemouth','Борнмут'),
('Wolverhampton Wanderers FC','Wolves'),
('Wolverhampton Wanderers FC','Вулверхэмптон'),
('Wolves','Wolves'),
('Wolves','Вулверхэмптон'),
('Fulham FC','Fulham'),
('Fulham FC','Фулхэм'),
('Fulham','Fulham'),
('Fulham','Фулхэм'),
('Newcastle United FC','Newcastle'),
('Newcastle United FC','Ньюкасл'),
('Newcastle','Newcastle'),
('Newcastle','Ньюкасл'),
('Nottingham Forest FC','Nottingham Forest'),
('Nottingham Forest FC','Ноттингем Форест'),
('Nottingham Forest','Nottingham Forest'),
('Nottingham Forest','Ноттингем Форест'),
('Nottingham','Nottingham Forest'),
('Nottingham','Ноттингем Форест'),
('Sunderland AFC','Sunderland'),
('Sunderland AFC','Сандерленд'),
('Sunderland','Sunderland'),
('Sunderland','Сандерленд'),
('Leeds United FC','Leeds'),
('Leeds United FC','Лидс'),
('Leeds','Leeds'),
('Leeds','Лидс'),
('Leeds United','Leeds'),
('Leeds United','Лидс'),
('Everton FC','Everton'),
('Everton FC','Эвертон'),
('Everton','Everton'),
('Everton','Эвертон'),
('Crystal Palace FC','Crystal Palace'),
('Crystal Palace FC','Кристал Пэлас'),
('Crystal Palace','Crystal Palace'),
('Crystal Palace','Кристал Пэлас'),
('Coventry City FC','Coventry'),
('Coventry City FC','Ковентри'),
('Coventry','Coventry'),
('Coventry','Ковентри'),
('Coventry City','Coventry'),
('Coventry City','Ковентри'),
('Hull City AFC','Hull City'),
('Hull City AFC','Халл Сити'),
('Hull City','Hull City'),
('Hull City','Халл Сити'),
('Ipswich Town FC','Ipswich'),
('Ipswich Town FC','Ипсвич'),
('Ipswich','Ipswich'),
('Ipswich','Ипсвич'),
('Ipswich Town','Ipswich'),
('Ipswich Town','Ипсвич'),
('Athletic Club','Athletic Club'),
('Athletic Club','Атлетик'),
('Athletic Club','Атлетик Бильбао'),
('Athletic','Athletic Club'),
('Athletic','Атлетик'),
('Athletic','Атлетик Бильбао'),
('CA Osasuna','Osasuna'),
('CA Osasuna','Осасуна'),
('Osasuna','Osasuna'),
('Osasuna','Осасуна'),
('Deportivo Alavés','Alavés'),
('Deportivo Alavés','Алавес'),
('Alavés','Alavés'),
('Alavés','Алавес'),
('Elche CF','Elche'),
('Elche CF','Эльче'),
('Elche','Elche'),
('Elche','Эльче'),
('Getafe CF','Getafe'),
('Getafe CF','Хетафе'),
('Getafe','Getafe'),
('Getafe','Хетафе'),
('Girona FC','Girona'),
('Girona FC','Жирона'),
('Girona','Girona'),
('Girona','Жирона'),
('Levante UD','Levante'),
('Levante UD','Леванте'),
('Levante','Levante'),
('Levante','Леванте'),
('Rayo Vallecano de Madrid','Rayo Vallecano'),
('Rayo Vallecano de Madrid','Райо Вальекано'),
('Rayo Vallecano','Rayo Vallecano'),
('Rayo Vallecano','Райо Вальекано'),
('RC Celta de Vigo','Celta'),
('RC Celta de Vigo','Сельта'),
('Celta','Celta'),
('Celta','Сельта'),
('RCD Espanyol de Barcelona','Espanyol'),
('RCD Espanyol de Barcelona','Эспаньол'),
('Espanyol','Espanyol'),
('Espanyol','Эспаньол'),
('RCD Mallorca','Mallorca'),
('RCD Mallorca','Мальорка'),
('Mallorca','Mallorca'),
('Mallorca','Мальорка'),
('Real Betis Balompié','Real Betis'),
('Real Betis Balompié','Бетис'),
('Real Betis Balompié','Реал Бетис'),
('Real Betis','Real Betis'),
('Real Betis','Бетис'),
('Real Betis','Реал Бетис'),
('Real Sociedad de Fútbol','Real Sociedad'),
('Real Sociedad de Fútbol','Реал Сосьедад'),
('Real Sociedad','Real Sociedad'),
('Real Sociedad','Реал Сосьедад'),
('Real Oviedo','Real Oviedo'),
('Real Oviedo','Реал Овьедо'),
('Sevilla FC','Sevilla'),
('Sevilla FC','Севилья'),
('Sevilla','Sevilla'),
('Sevilla','Севилья'),
('Valencia CF','Valencia'),
('Valencia CF','Валенсия'),
('Valencia','Valencia'),
('Valencia','Валенсия'),
('Villarreal CF','Villarreal'),
('Villarreal CF','Вильярреал'),
('Villarreal','Villarreal'),
('Villarreal','Вильярреал'),
('Málaga CF','Málaga'),
('Málaga CF','Малага'),
('Málaga','Málaga'),
('Málaga','Малага'),
('RC Deportivo La Coruña','Deportivo'),
('RC Deportivo La Coruña','Депортиво'),
('RC Deportivo La Coruña','Депортиво Ла-Корунья'),
('Deportivo','Deportivo'),
('Deportivo','Депортиво'),
('Deportivo','Депортиво Ла-Корунья'),
('Real Racing Club de Santander','Racing Santander'),
('Real Racing Club de Santander','Расинг'),
('Real Racing Club de Santander','Расинг Сантандер'),
('Racing Santander','Racing Santander'),
('Racing Santander','Расинг'),
('Racing Santander','Расинг Сантандер'),
('Santander','Racing Santander'),
('Santander','Расинг'),
('Santander','Расинг Сантандер'),
('FC Bayern München','Bayern'),
('FC Bayern München','Бавария'),
('Bayern','Bayern'),
('Bayern','Бавария'),
('Borussia Dortmund','Dortmund'),
('Borussia Dortmund','Боруссия Д'),
('Borussia Dortmund','Боруссия Дортмунд'),
('Dortmund','Dortmund'),
('Dortmund','Боруссия Д'),
('Dortmund','Боруссия Дортмунд'),
('Borussia Mönchengladbach','Mönchengladbach'),
('Borussia Mönchengladbach','Боруссия М'),
('Borussia Mönchengladbach','Боруссия Мёнхенгладбах'),
('Mönchengladbach','Mönchengladbach'),
('Mönchengladbach','Боруссия М'),
('Mönchengladbach','Боруссия Мёнхенгладбах'),
('M''gladbach','Mönchengladbach'),
('M''gladbach','Боруссия М'),
('M''gladbach','Боруссия Мёнхенгладбах'),
('Bayer 04 Leverkusen','Leverkusen'),
('Bayer 04 Leverkusen','Байер'),
('Bayer 04 Leverkusen','Байер Леверкузен'),
('Leverkusen','Leverkusen'),
('Leverkusen','Байер'),
('Leverkusen','Байер Леверкузен'),
('RB Leipzig','RB Leipzig'),
('RB Leipzig','РБ Лейпциг'),
('Eintracht Frankfurt','Frankfurt'),
('Eintracht Frankfurt','Айнтрахт'),
('Eintracht Frankfurt','Айнтрахт Франкфурт'),
('Frankfurt','Frankfurt'),
('Frankfurt','Айнтрахт'),
('Frankfurt','Айнтрахт Франкфурт'),
('VfL Wolfsburg','Wolfsburg'),
('VfL Wolfsburg','Вольфсбург'),
('Wolfsburg','Wolfsburg'),
('Wolfsburg','Вольфсбург'),
('SV Werder Bremen','Werder Bremen'),
('SV Werder Bremen','Вердер'),
('Werder Bremen','Werder Bremen'),
('Werder Bremen','Вердер'),
('Bremen','Werder Bremen'),
('Bremen','Вердер'),
('VfB Stuttgart','Stuttgart'),
('VfB Stuttgart','Штутгарт'),
('Stuttgart','Stuttgart'),
('Stuttgart','Штутгарт'),
('TSG 1899 Hoffenheim','Hoffenheim'),
('TSG 1899 Hoffenheim','Хоффенхайм'),
('Hoffenheim','Hoffenheim'),
('Hoffenheim','Хоффенхайм'),
('1. FSV Mainz 05','Mainz'),
('1. FSV Mainz 05','Майнц'),
('Mainz','Mainz'),
('Mainz','Майнц'),
('1. FC Köln','Köln'),
('1. FC Köln','Кёльн'),
('Köln','Köln'),
('Köln','Кёльн'),
('1. FC Union Berlin','Union Berlin'),
('1. FC Union Berlin','Унион Берлин'),
('Union Berlin','Union Berlin'),
('Union Berlin','Унион Берлин'),
('1. FC Heidenheim 1846','Heidenheim'),
('1. FC Heidenheim 1846','Хайденхайм'),
('Heidenheim','Heidenheim'),
('Heidenheim','Хайденхайм'),
('SC Freiburg','Freiburg'),
('SC Freiburg','Фрайбург'),
('Freiburg','Freiburg'),
('Freiburg','Фрайбург'),
('FC Augsburg','Augsburg'),
('FC Augsburg','Аугсбург'),
('Augsburg','Augsburg'),
('Augsburg','Аугсбург'),
('Hamburger SV','Hamburg'),
('Hamburger SV','Гамбург'),
('Hamburg','Hamburg'),
('Hamburg','Гамбург'),
('HSV','Hamburg'),
('HSV','Гамбург'),
('FC St. Pauli 1910','St. Pauli'),
('FC St. Pauli 1910','Санкт-Паули'),
('St. Pauli','St. Pauli'),
('St. Pauli','Санкт-Паули'),
('FC Schalke 04','Schalke'),
('FC Schalke 04','Шальке'),
('Schalke','Schalke'),
('Schalke','Шальке'),
('SC Paderborn 07','Paderborn'),
('SC Paderborn 07','Падерборн'),
('Paderborn','Paderborn'),
('Paderborn','Падерборн'),
('SC Paderborn','Paderborn'),
('SC Paderborn','Падерборн'),
('SV 07 Elversberg','Elversberg'),
('SV 07 Elversberg','Эльверсберг'),
('Elversberg','Elversberg'),
('Elversberg','Эльверсберг'),
('AC Milan','AC Milan'),
('AC Milan','Милан'),
('Milan','AC Milan'),
('Milan','Милан'),
('FC Internazionale Milano','Inter'),
('FC Internazionale Milano','Интер'),
('Inter','Inter'),
('Inter','Интер'),
('Juventus FC','Juventus'),
('Juventus FC','Ювентус'),
('Juventus','Juventus'),
('Juventus','Ювентус'),
('SSC Napoli','Napoli'),
('SSC Napoli','Наполи'),
('Napoli','Napoli'),
('Napoli','Наполи'),
('Atalanta BC','Atalanta'),
('Atalanta BC','Аталанта'),
('Atalanta','Atalanta'),
('Atalanta','Аталанта'),
('Bologna FC 1909','Bologna'),
('Bologna FC 1909','Болонья'),
('Bologna','Bologna'),
('Bologna','Болонья'),
('AS Roma','Roma'),
('AS Roma','Рома'),
('Roma','Roma'),
('Roma','Рома'),
('SS Lazio','Lazio'),
('SS Lazio','Лацио'),
('Lazio','Lazio'),
('Lazio','Лацио'),
('ACF Fiorentina','Fiorentina'),
('ACF Fiorentina','Фиорентина'),
('Fiorentina','Fiorentina'),
('Fiorentina','Фиорентина'),
('Como 1907','Como'),
('Como 1907','Комо'),
('Como','Como'),
('Como','Комо'),
('Cagliari Calcio','Cagliari'),
('Cagliari Calcio','Кальяри'),
('Cagliari','Cagliari'),
('Cagliari','Кальяри'),
('Genoa CFC','Genoa'),
('Genoa CFC','Дженоа'),
('Genoa','Genoa'),
('Genoa','Дженоа'),
('Hellas Verona FC','Verona'),
('Hellas Verona FC','Верона'),
('Verona','Verona'),
('Verona','Верона'),
('Parma Calcio 1913','Parma'),
('Parma Calcio 1913','Парма'),
('Parma','Parma'),
('Parma','Парма'),
('Udinese Calcio','Udinese'),
('Udinese Calcio','Удинезе'),
('Udinese','Udinese'),
('Udinese','Удинезе'),
('Torino FC','Torino'),
('Torino FC','Торино'),
('Torino','Torino'),
('Torino','Торино'),
('US Sassuolo Calcio','Sassuolo'),
('US Sassuolo Calcio','Сассуоло'),
('Sassuolo','Sassuolo'),
('Sassuolo','Сассуоло'),
('US Lecce','Lecce'),
('US Lecce','Лечче'),
('Lecce','Lecce'),
('Lecce','Лечче'),
('US Cremonese','Cremonese'),
('US Cremonese','Кремонезе'),
('Cremonese','Cremonese'),
('Cremonese','Кремонезе'),
('AC Pisa 1909','Pisa'),
('AC Pisa 1909','Пиза'),
('Pisa','Pisa'),
('Pisa','Пиза'),
('Olympique de Marseille','Marseille'),
('Olympique de Marseille','Марсель'),
('Marseille','Marseille'),
('Marseille','Марсель'),
('Olympique Lyonnais','Lyon'),
('Olympique Lyonnais','Лион'),
('Lyon','Lyon'),
('Lyon','Лион'),
('Olympique Lyon','Lyon'),
('Olympique Lyon','Лион'),
('AS Monaco FC','Monaco'),
('AS Monaco FC','Монако'),
('Monaco','Monaco'),
('Monaco','Монако'),
('Lille OSC','Lille'),
('Lille OSC','Лилль'),
('Lille','Lille'),
('Lille','Лилль'),
('Racing Club de Lens','Lens'),
('Racing Club de Lens','Ланс'),
('Lens','Lens'),
('Lens','Ланс'),
('RC Lens','Lens'),
('RC Lens','Ланс'),
('OGC Nice','Nice'),
('OGC Nice','Ницца'),
('Nice','Nice'),
('Nice','Ницца'),
('Stade Rennais FC 1901','Rennes'),
('Stade Rennais FC 1901','Ренн'),
('Rennes','Rennes'),
('Rennes','Ренн'),
('Stade Rennais','Rennes'),
('Stade Rennais','Ренн'),
('Stade Brestois 29','Brest'),
('Stade Brestois 29','Брест'),
('Brest','Brest'),
('Brest','Брест'),
('RC Strasbourg Alsace','Strasbourg'),
('RC Strasbourg Alsace','Страсбур'),
('Strasbourg','Strasbourg'),
('Strasbourg','Страсбур'),
('Toulouse FC','Toulouse'),
('Toulouse FC','Тулуза'),
('Toulouse','Toulouse'),
('Toulouse','Тулуза'),
('Le Havre AC','Le Havre'),
('Le Havre AC','Гавр'),
('Le Havre','Le Havre'),
('Le Havre','Гавр'),
('FC Nantes','Nantes'),
('FC Nantes','Нант'),
('Nantes','Nantes'),
('Nantes','Нант'),
('AJ Auxerre','Auxerre'),
('AJ Auxerre','Осер'),
('Auxerre','Auxerre'),
('Auxerre','Осер'),
('Angers SCO','Angers'),
('Angers SCO','Анже'),
('Angers','Angers'),
('Angers','Анже'),
('FC Lorient','Lorient'),
('FC Lorient','Лорьян'),
('Lorient','Lorient'),
('Lorient','Лорьян'),
('FC Metz','Metz'),
('FC Metz','Мец'),
('Metz','Metz'),
('Metz','Мец'),
('Paris FC','Paris FC'),
('Paris FC','Париж'),
('ES Troyes AC','Troyes'),
('ES Troyes AC','Труа'),
('Troyes','Troyes'),
('Troyes','Труа'),
('Le Mans FC','Le Mans'),
('Le Mans FC','Ле-Ман'),
('Le Mans','Le Mans'),
('Le Mans','Ле-Ман'),
('AFC Ajax','Ajax'),
('AFC Ajax','Аякс'),
('Ajax','Ajax'),
('Ajax','Аякс'),
('PSV','PSV'),
('PSV','ПСВ'),
('Sport Lisboa e Benfica','Benfica'),
('Sport Lisboa e Benfica','Бенфика'),
('Benfica','Benfica'),
('Benfica','Бенфика'),
('Sporting Clube de Portugal','Sporting CP'),
('Sporting Clube de Portugal','Спортинг'),
('Sporting CP','Sporting CP'),
('Sporting CP','Спортинг'),
('Club Brugge KV','Club Brugge'),
('Club Brugge KV','Брюгге'),
('Club Brugge','Club Brugge'),
('Club Brugge','Брюгге'),
('Royale Union Saint-Gilloise','Union SG'),
('Royale Union Saint-Gilloise','Юнион'),
('Royale Union Saint-Gilloise','Юнион Сен-Жиллуаз'),
('Union SG','Union SG'),
('Union SG','Юнион'),
('Union SG','Юнион Сен-Жиллуаз'),
('FC København','Copenhagen'),
('FC København','Копенгаген'),
('Copenhagen','Copenhagen'),
('Copenhagen','Копенгаген'),
('FK Bodø/Glimt','Bodø/Glimt'),
('FK Bodø/Glimt','Будё-Глимт'),
('Bodø/Glimt','Bodø/Glimt'),
('Bodø/Glimt','Будё-Глимт'),
('FK Kairat','Kairat'),
('FK Kairat','Кайрат'),
('Kairat','Kairat'),
('Kairat','Кайрат'),
('Galatasaray SK','Galatasaray'),
('Galatasaray SK','Галатасарай'),
('Galatasaray','Galatasaray'),
('Galatasaray','Галатасарай'),
('PAE Olympiakos SFP','Olympiacos'),
('PAE Olympiakos SFP','Олимпиакос'),
('Olympiacos','Olympiacos'),
('Olympiacos','Олимпиакос'),
('Paphos FC','Paphos'),
('Paphos FC','Пафос'),
('Paphos','Paphos'),
('Paphos','Пафос'),
('Qarabağ Ağdam FK','Qarabağ'),
('Qarabağ Ağdam FK','Карабах'),
('Qarabağ','Qarabağ'),
('Qarabağ','Карабах'),
('SK Slavia Praha','Slavia Prague'),
('SK Slavia Praha','Славия'),
('SK Slavia Praha','Славия Прага'),
('Slavia Prague','Slavia Prague'),
('Slavia Prague','Славия'),
('Slavia Prague','Славия Прага'),
('Slavia Praha','Slavia Prague'),
('Slavia Praha','Славия'),
('Slavia Praha','Славия Прага'),
('AC Monza','Monza'),
('AC Monza','Монца'),
('Monza','Monza'),
('Monza','Монца'),
('FC Porto','Porto'),
('FC Porto','Порту'),
('Porto','Porto'),
('Porto','Порту'),
('Fenerbahçe SK','Fenerbahçe'),
('Fenerbahçe SK','Фенербахче'),
('Fenerbahçe','Fenerbahçe'),
('Fenerbahçe','Фенербахче'),
('Feyenoord Rotterdam','Feyenoord'),
('Feyenoord Rotterdam','Фейеноорд'),
('Feyenoord','Feyenoord'),
('Feyenoord','Фейеноорд'),
('FK Shakhtar Donetsk','Shakhtar'),
('FK Shakhtar Donetsk','Шахтёр'),
('FK Shakhtar Donetsk','Шахтёр Донецк'),
('Shakhtar','Shakhtar'),
('Shakhtar','Шахтёр'),
('Shakhtar','Шахтёр Донецк'),
('Shaktar','Shakhtar'),
('Shaktar','Шахтёр'),
('Shaktar','Шахтёр Донецк'),
('Frosinone Calcio','Frosinone'),
('Frosinone Calcio','Фрозиноне'),
('Frosinone','Frosinone'),
('Frosinone','Фрозиноне'),
('LASK Linz','LASK'),
('LASK Linz','ЛАСК'),
('LASK','LASK'),
('LASK','ЛАСК'),
('PAE AEK','AEK Athens'),
('PAE AEK','АЕК'),
('PAE AEK','АЕК Афины'),
('AEK Athens','AEK Athens'),
('AEK Athens','АЕК'),
('AEK Athens','АЕК Афины'),
('Sabah FK','Sabah'),
('Sabah FK','Сабах'),
('Sabah','Sabah'),
('Sabah','Сабах'),
('ŠK Slovan Bratislava','Slovan Bratislava'),
('ŠK Slovan Bratislava','Слован'),
('ŠK Slovan Bratislava','Слован Братислава'),
('Slovan Bratislava','Slovan Bratislava'),
('Slovan Bratislava','Слован'),
('Slovan Bratislava','Слован Братислава'),
('Sl. Bratislava','Slovan Bratislava'),
('Sl. Bratislava','Слован'),
('Sl. Bratislava','Слован Братислава'),
('Venezia FC','Venezia'),
('Venezia FC','Венеция'),
('Venezia','Venezia'),
('Venezia','Венеция'),
('Viking FK','Viking'),
('Viking FK','Викинг'),
('Viking','Viking'),
('Viking','Викинг'),
('Зенит','Zenit'),
('Зенит','Зенит'),
('Zenit','Zenit'),
('Zenit','Зенит'),
('Спартак','Spartak Moscow'),
('Спартак','Спартак'),
('Спартак','Спартак Москва'),
('Spartak Moscow','Spartak Moscow'),
('Spartak Moscow','Спартак'),
('Spartak Moscow','Спартак Москва'),
('Динамо Москва','Dynamo Moscow'),
('Динамо Москва','Динамо Москва'),
('Dynamo Moscow','Dynamo Moscow'),
('Dynamo Moscow','Динамо Москва'),
('Краснодар','Krasnodar'),
('Краснодар','Краснодар'),
('Krasnodar','Krasnodar'),
('Krasnodar','Краснодар')
) labels(source_name,alias) on lower(labels.source_name)=lower(c.name) or lower(labels.source_name)=lower(c.short_name)
on conflict do nothing;
CREATE OR REPLACE FUNCTION public.get_football_statistics(p_kind text DEFAULT 'matches'::text, p_filters jsonb DEFAULT '{}'::jsonb, p_offset integer DEFAULT 0, p_limit integer DEFAULT 12)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  f jsonb := coalesce(p_filters,'{}'::jsonb);
  q text := left(btrim(coalesce(f->>'query','')),80);
  league text := left(coalesce(f->>'league',''),120);
  team_filter text := left(coalesce(f->>'team',''),160);
  competition_id_filter bigint;
  club_id_filter bigint;
  from_day date := nullif(f->>'from','')::date;
  to_day date := nullif(f->>'to','')::date;
  min_votes integer := coalesce(nullif(f->>'min_votes','')::integer,1);
  ordering text := coalesce(nullif(f->>'sort',''),'average');
  page_size integer := least(greatest(coalesce(p_limit,12),1),24);
  page_offset integer := greatest(coalesce(p_offset,0),0);
  result jsonb;
  confirmed_only boolean := false;
begin
  if f ? 'confirmed_only' and jsonb_typeof(f->'confirmed_only') <> 'boolean' then
    raise exception using errcode='22023',message='invalid_statistics_filters';
  end if;
  confirmed_only := coalesce((f->>'confirmed_only')::boolean,false);
  if (nullif(f->>'competition_id','') is not null and f->>'competition_id' !~ '^[1-9][0-9]{0,14}$')
     or (nullif(f->>'club_id','') is not null and f->>'club_id' !~ '^[1-9][0-9]{0,14}$') then
    raise exception using errcode='22023',message='invalid_statistics_filters';
  end if;
  competition_id_filter := nullif(f->>'competition_id','')::bigint;
  club_id_filter := nullif(f->>'club_id','')::bigint;
  if p_kind not in ('matches','clubs','players','leagues') or jsonb_typeof(f)<>'object'
     or min_votes not between 1 and 1000000 or from_day>to_day
     or ordering not in ('average','votes','recent') or page_offset>100000 then
    raise exception using errcode='22023',message='invalid_statistics_filters';
  end if;
  with base as materialized (
    select r.id,r.user_id,r.match_id,r.match_rating,m.home_team_name,m.away_team_name,
      m.home_club_id,m.away_club_id,m.competition_id,m.league_name,m.match_date,m.home_score,m.away_score
    from private.community_public_match_votes r join public.users u on u.id=r.user_id join public.matches m on m.id=r.match_id
    where r.is_public and u.is_public and m.status='finished'
      and (competition_id_filter is null or m.competition_id=competition_id_filter)
      and (p_kind='players' or club_id_filter is null or club_id_filter in (m.home_club_id,m.away_club_id))
      and (competition_id_filter is not null or league='' or m.league_name=league)
      and (p_kind='players' or club_id_filter is not null or team_filter='' or team_filter in (m.home_team_name,m.away_team_name))
      and (from_day is null or m.match_date>=from_day::timestamp at time zone 'UTC')
      and (to_day is null or m.match_date<(to_day+1)::timestamp at time zone 'UTC')
  ), entries as (
    select b.match_id::text entity_key,b.match_id entity_id,
      b.home_team_name||' — '||b.away_team_name title,b.league_name subtitle,
      b.match_rating::numeric score,b.user_id,b.match_id,b.match_date,
      b.home_score,b.away_score,null::bigint player_id,null::boolean participation_verified
    from base b where p_kind='matches'
    union all
    select coalesce(b.competition_id::text,'legacy:'||b.league_name),b.competition_id,b.league_name,'Турнир',
      b.match_rating,b.user_id,b.match_id,b.match_date,null::smallint,null::smallint,null::bigint,null::boolean
    from base b where p_kind='leagues'
    union all
    select coalesce(c.id::text,t.name),c.id,coalesce(c.short_name,c.name,t.name),'Матчи клуба',
      b.match_rating,b.user_id,b.match_id,b.match_date,null::smallint,null::smallint,null::bigint,null::boolean
    from base b cross join lateral (values (b.home_club_id,b.home_team_name),(b.away_club_id,b.away_team_name)) t(id,name)
    left join public.clubs c on c.id=t.id where p_kind='clubs'
    union all
    select p.id::text,p.id,p.name,coalesce(pr.club_short_name,pr.team,'Клуб выступления не подтверждён'),pr.rating,b.user_id,b.match_id,b.match_date,null::smallint,null::smallint,p.id,pr.participation_verified
    from base b join private.community_player_performances pr on pr.match_id=b.match_id and pr.user_id=b.user_id
    join public.players p on p.id=pr.player_id where p_kind='players'
      and (not confirmed_only or pr.participation_verified)
      and (club_id_filter is null or pr.club_id=club_id_filter)
      and (club_id_filter is not null or team_filter='' or pr.team=team_filter)
  ), grouped as materialized (
    select e.entity_key,min(e.entity_id) entity_id,min(e.title) title,case when p_kind='players' and count(distinct e.subtitle)>1 then 'Несколько клубов в выбранном периоде' else min(e.subtitle) end subtitle,
      round(avg(e.score),1) average,count(*) votes,count(distinct e.user_id) voters,
      count(distinct e.match_id) matches,max(e.match_date) latest,
      count(*) filter(where p_kind='players' and not e.participation_verified) unverified_votes,
      max(e.home_score) home_score,max(e.away_score) away_score
    from entries e where q='' or position(lower(q) in lower(e.title||' '||coalesce(e.subtitle,'')))>0
      or (p_kind='clubs' and exists(select 1 from public.club_aliases ca where ca.club_id in (e.entity_id) and position(replace(lower(q),'ё','е') in replace(lower(ca.alias),'ё','е'))>0))
      or (p_kind='leagues' and exists(select 1 from public.competitions cp where cp.id=e.entity_id and position(lower(q) in case cp.code when 'CL' then 'лига чемпионов' when 'PL' then 'апл английская премьер-лига' when 'PD' then 'ла лига' when 'BL1' then 'бундеслига' when 'SA' then 'серия а' when 'FL1' then 'лига 1' when 'EL' then 'лига европы' else '' end)>0))
      or (p_kind='matches' and exists(select 1 from public.matches sm where sm.id=e.match_id and (exists(select 1 from public.club_aliases ca where ca.club_id in (sm.home_club_id,sm.away_club_id) and position(replace(lower(q),'ё','е') in replace(lower(ca.alias),'ё','е'))>0) or exists(select 1 from public.competitions cp where cp.id=sm.competition_id and position(lower(q) in case cp.code when 'CL' then 'лига чемпионов' when 'PL' then 'апл английская премьер-лига' when 'PD' then 'ла лига' when 'BL1' then 'бундеслига' when 'SA' then 'серия а' when 'FL1' then 'лига 1' when 'EL' then 'лига европы' else '' end)>0))))
      or (p_kind='players' and e.participation_verified and exists(select 1 from public.clubs sc where coalesce(sc.short_name,sc.name)=e.subtitle and exists(select 1 from public.club_aliases ca where ca.club_id in (sc.id) and position(replace(lower(q),'ё','е') in replace(lower(ca.alias),'ё','е'))>0)))
    group by e.entity_key having count(*)>=min_votes
  ), selected_votes as materialized (
    select distinct e.match_id,e.user_id from entries e join grouped g using(entity_key)
  ), ranked as (
    select g.*,row_number() over(order by
      case when ordering='average' then g.average end desc,
      case when ordering='votes' then g.votes end desc,
      case when ordering='recent' then g.latest end desc,
      g.votes desc,g.average desc,g.entity_key) rank from grouped g
  ), page as (select * from ranked order by rank limit page_size offset page_offset),
  enriched as (
    select p.*,
      m.home_club_id,m.away_club_id,m.home_team_name,m.away_team_name,
      case when ma.id is null then null else jsonb_build_object(
        'id',ma.id,'asset_type',ma.asset_type,'url',coalesce(ma.storage_url,ma.source_url),
        'source_provider',ma.source_provider,'license_name',ma.license_name,'license_url',ma.license_url,
        'attribution',ma.attribution,'usage_status',ma.usage_status) end media
    from page p
    left join public.matches m on p_kind='matches' and m.id=p.entity_id
    left join public.clubs c on p_kind='clubs' and c.id=p.entity_id
    left join public.players pl on p_kind='players' and pl.id=p.entity_id
    left join public.competitions cp on p_kind='leagues' and cp.id=p.entity_id
    left join public.media_assets ma on ma.id=case p_kind when 'clubs' then c.logo_asset_id
      when 'players' then pl.photo_asset_id when 'leagues' then cp.logo_asset_id end
      and public.is_displayable_media_asset(ma)
  )
  select jsonb_build_object(
    'items',coalesce((select jsonb_agg(to_jsonb(p) order by p.rank) from enriched p),'[]'::jsonb),
    'total',(select count(*) from grouped),
    'has_more',(select count(*)>page_offset+page_size from grouped),
    'next_offset',page_offset+page_size,
    'competitions',coalesce((select jsonb_agg(to_jsonb(x) order by x.name,x.id) from (
      select distinct cp.id,coalesce(cp.short_name,cp.name) name from public.matches m
      join public.competitions cp on cp.id=m.competition_id order by name,cp.id limit 200) x),'[]'::jsonb),
    'clubs',coalesce((select jsonb_agg(to_jsonb(x) order by x.name,x.id) from (
      select c.id,coalesce(c.short_name,c.name) name,array_agg(distinct m.competition_id) filter(where m.competition_id is not null) competition_ids
      from public.matches m cross join lateral (values(m.home_club_id),(m.away_club_id)) t(id)
      join public.clubs c on c.id=t.id group by c.id order by name,c.id limit 1000) x),'[]'::jsonb),
    'summary',jsonb_build_object('matches',(select count(distinct match_id) from selected_votes),'votes',(select count(*) from selected_votes),'voters',(select count(distinct user_id) from selected_votes),
      'performance_votes',case when p_kind='players' then coalesce((select sum(votes) from grouped),0) else null end,
      'unverified_performance_votes',case when p_kind='players' then coalesce((select sum(unverified_votes) from grouped),0) else null end,
      'confirmed_only',p_kind='players' and confirmed_only,
      'excluded_unverified_performance_votes',case when p_kind='players' and confirmed_only then (
        select count(*) from base b join private.community_player_performances pr on pr.match_id=b.match_id and pr.user_id=b.user_id
        join public.players p on p.id=pr.player_id where not pr.participation_verified and club_id_filter is null and team_filter=''
          and (q='' or position(lower(q) in lower(p.name||' Клуб выступления не подтверждён'))>0)
      ) else 0 end),
    'leagues',coalesce((select jsonb_agg(x.league_name order by x.league_name) from (select distinct league_name from public.matches limit 200) x),'[]'::jsonb),
    'teams',coalesce((select jsonb_agg(x.name order by x.name) from (select home_team_name name from public.matches union select away_team_name from public.matches limit 1000) x),'[]'::jsonb)
  ) into result;
  return result;
end $function$
;

CREATE OR REPLACE FUNCTION public.get_matches_page(p_status text DEFAULT 'all'::text, p_league text DEFAULT NULL::text, p_query text DEFAULT NULL::text, p_limit integer DEFAULT 24, p_offset integer DEFAULT 0)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  normalized_status text := lower(btrim(coalesce(p_status, 'all')));
  normalized_league text := nullif(btrim(coalesce(p_league, '')), '');
  normalized_query text := left(lower(btrim(coalesce(p_query, ''))), 80);
  normalized_limit integer := least(greatest(coalesce(p_limit, 24), 1), 48);
  normalized_offset integer := least(greatest(coalesce(p_offset, 0), 0), 10000);
  result jsonb;
begin
  if normalized_status not in ('all', 'live', 'scheduled', 'finished', 'postponed', 'cancelled') then
    raise exception using errcode = '22023', message = 'invalid_match_status';
  end if;
  if normalized_league = 'all' then normalized_league := null; end if;
  with filtered as materialized (
    select m.id, m.competition_id, m.league_name, m.home_team_name, m.away_team_name,
      m.home_club_id, m.away_club_id, m.match_date, m.status, m.home_score, m.away_score,
      m.external_id, m.league_code, m.matchday, m.season,
      case m.status when 'live' then 0 when 'scheduled' then 1 when 'finished' then 2 else 3 end as sort_status,
      case when m.status = 'scheduled' and m.match_date < current_timestamp then 1 else 0 end as sort_stale,
      case when m.status in ('live', 'scheduled') and m.match_date >= current_timestamp then m.match_date end as sort_upcoming,
      case when m.status = 'finished' or (m.status = 'scheduled' and m.match_date < current_timestamp) then m.match_date end as sort_recent
    from public.matches m
    where (normalized_status = 'all' or m.status = normalized_status)
      and (normalized_league is null or m.league_name = normalized_league)
      and (normalized_query = '' or lower(m.home_team_name) like '%' || normalized_query || '%'
        or lower(m.away_team_name) like '%' || normalized_query || '%' or lower(m.league_name) like '%' || normalized_query || '%' or exists(select 1 from public.club_aliases ca where ca.club_id in (m.home_club_id,m.away_club_id) and position(replace(lower(normalized_query),'ё','е') in replace(lower(ca.alias),'ё','е'))>0) or exists(select 1 from public.competitions cp where cp.id=m.competition_id and position(lower(normalized_query) in case cp.code when 'CL' then 'лига чемпионов' when 'PL' then 'апл английская премьер-лига' when 'PD' then 'ла лига' when 'BL1' then 'бундеслига' when 'SA' then 'серия а' when 'FL1' then 'лига 1' when 'EL' then 'лига европы' else '' end)>0))
  ), page as materialized (
    select * from filtered order by sort_status, sort_stale, sort_upcoming asc nulls last, sort_recent desc nulls last, id desc
    limit normalized_limit offset normalized_offset
  ), totals as (select count(*)::integer as total from filtered),
  league_values as (select distinct m.league_name from public.matches m where nullif(btrim(m.league_name), '') is not null)
  select jsonb_build_object(
    'items', coalesce((select jsonb_agg(jsonb_build_object(
      'id', p.id, 'competition_id', p.competition_id, 'league_name', p.league_name,
      'home_team_name', p.home_team_name, 'away_team_name', p.away_team_name,
      'home_club_id', p.home_club_id, 'away_club_id', p.away_club_id,
      'match_date', p.match_date, 'status', p.status, 'home_score', p.home_score, 'away_score', p.away_score,
      'external_id', p.external_id, 'league_code', p.league_code, 'matchday', p.matchday, 'season', p.season
    ) order by p.sort_status, p.sort_stale, p.sort_upcoming asc nulls last, p.sort_recent desc nulls last, p.id desc) from page p), '[]'::jsonb),
    'total', totals.total, 'has_more', normalized_offset + (select count(*) from page) < totals.total,
    'next_offset', normalized_offset + (select count(*) from page),
    'leagues', coalesce((select jsonb_agg(l.league_name order by l.league_name) from league_values l), '[]'::jsonb)
  ) into result from totals;
  return result;
end
$function$
;

CREATE OR REPLACE FUNCTION public.get_profile_diary(p_user_id uuid, p_filters jsonb DEFAULT '{}'::jsonb, p_cursor jsonb DEFAULT NULL::jsonb, p_limit integer DEFAULT 8)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  f jsonb := coalesce(p_filters, '{}'::jsonb);
  q text := left(btrim(coalesce(f->>'query','')),80);
  league text := left(coalesce(f->>'league',''),120);
  team text := left(coalesce(f->>'team',''),160);
  competition_id_filter bigint;
  club_id_filter bigint;
  from_day date := nullif(f->>'from','')::date;
  to_day date := nullif(f->>'to','')::date;
  min_rating integer := coalesce(nullif(f->>'min_rating','')::integer,1);
  max_rating integer := coalesce(nullif(f->>'max_rating','')::integer,10);
  home_goals integer := nullif(f->>'home_score','')::integer;
  away_goals integer := nullif(f->>'away_score','')::integer;
  version_two boolean := coalesce(f->>'v','')='2';
  cursor_time timestamptz := (case when version_two then p_cursor->>'match_date' else p_cursor->>'created_at' end)::timestamptz;
  cursor_id bigint := (p_cursor->>'id')::bigint;
  page_size integer := least(greatest(coalesce(p_limit,8),1),24);
  result jsonb;
begin
  if (nullif(f->>'competition_id','') is not null and f->>'competition_id' !~ '^[1-9][0-9]{0,14}$')
     or (nullif(f->>'club_id','') is not null and f->>'club_id' !~ '^[1-9][0-9]{0,14}$') then
    raise exception using errcode='22023',message='invalid_diary_filters';
  end if;
  competition_id_filter := nullif(f->>'competition_id','')::bigint;
  club_id_filter := nullif(f->>'club_id','')::bigint;
  if p_user_id is null or jsonb_typeof(f)<>'object'
     or min_rating not between 1 and 10 or max_rating not between min_rating and 10
     or from_day>to_day or home_goals not between 0 and 99 or away_goals not between 0 and 99
     or (cursor_time is null)<>(cursor_id is null) then
    raise exception using errcode='22023',message='invalid_diary_filters';
  end if;
  if not exists(select 1 from public.users u where u.id=p_user_id) then
    return null;
  end if;
  with visible as materialized (
    select r.id,r.user_id,r.match_id,r.match_rating,r.is_public,r.created_at,
      m.home_team_name,m.away_team_name,m.league_name,m.match_date,m.home_score,m.away_score,
      m.competition_id,m.home_club_id,m.away_club_id,btrim(coalesce(r.comment,''))<>'' has_review
    from public.ratings r join public.matches m on m.id=r.match_id
    where r.user_id=p_user_id and (r.is_public or r.user_id=(select auth.uid()))
  ), filtered as materialized (
    select * from visible v
    where (q='' or position(lower(q) in lower(v.home_team_name||' '||v.away_team_name))>0 or exists(select 1 from public.club_aliases ca where ca.club_id in (v.home_club_id,v.away_club_id) and position(replace(lower(q),'ё','е') in replace(lower(ca.alias),'ё','е'))>0) or exists(select 1 from public.competitions cp where cp.id=v.competition_id and position(lower(q) in case cp.code when 'CL' then 'лига чемпионов' when 'PL' then 'апл английская премьер-лига' when 'PD' then 'ла лига' when 'BL1' then 'бундеслига' when 'SA' then 'серия а' when 'FL1' then 'лига 1' when 'EL' then 'лига европы' else '' end)>0))
      and (competition_id_filter is null or v.competition_id=competition_id_filter)
      and (club_id_filter is null or club_id_filter in (v.home_club_id,v.away_club_id))
      and (competition_id_filter is not null or league='' or v.league_name=league)
      and (club_id_filter is not null or team='' or team in (v.home_team_name,v.away_team_name))
      and v.match_rating between min_rating and max_rating
      and (from_day is null or v.match_date>=from_day::timestamp at time zone 'UTC')
      and (to_day is null or v.match_date<(to_day+1)::timestamp at time zone 'UTC')
      and (home_goals is null or v.home_score=home_goals)
      and (away_goals is null or v.away_score=away_goals)
  ), page_plus as materialized (
    select * from filtered v
    where cursor_time is null or ((case when version_two then v.match_date else v.created_at end),v.id)<(cursor_time,cursor_id)
    order by (case when version_two then v.match_date else v.created_at end) desc,v.id desc limit page_size+1
  ), page as materialized (
    select * from page_plus order by (case when version_two then match_date else created_at end) desc,id desc limit page_size
  )
  select jsonb_build_object(
    'items',coalesce((select jsonb_agg(to_jsonb(p) order by (case when version_two then p.match_date else p.created_at end) desc,p.id desc) from page p),'[]'::jsonb),
    'total',(select count(*) from filtered),
    'has_more',(select count(*)>page_size from page_plus),
    'next_cursor',(select jsonb_build_object(case when version_two then 'match_date' else 'created_at' end,
      case when version_two then match_date else created_at end,'id',id) from page
      order by (case when version_two then match_date else created_at end),id limit 1),
    'months',coalesce((select jsonb_agg(to_jsonb(x) order by x.month desc) from (
      select to_char(v.match_date at time zone 'UTC','YYYY-MM') as month,count(*) matches,
        round(avg(v.match_rating),1) average,count(*) filter(where v.has_review) reviews
      from filtered v where to_char(v.match_date at time zone 'UTC','YYYY-MM') in
        (select to_char(p.match_date at time zone 'UTC','YYYY-MM') from page p)
      group by 1) x),'[]'::jsonb),
    'competitions',coalesce((select jsonb_agg(to_jsonb(x) order by x.name,x.id) from (
      select distinct cp.id,coalesce(cp.short_name,cp.name) name from visible v
      join public.competitions cp on cp.id=v.competition_id order by name,cp.id limit 200) x),'[]'::jsonb),
    'clubs',coalesce((select jsonb_agg(to_jsonb(x) order by x.name,x.id) from (
      select c.id,coalesce(c.short_name,c.name) name,array_agg(distinct v.competition_id) filter(where v.competition_id is not null) competition_ids
      from visible v cross join lateral (values(v.home_club_id),(v.away_club_id)) t(id)
      join public.clubs c on c.id=t.id group by c.id order by name,c.id limit 1000) x),'[]'::jsonb),
    'leagues',coalesce((select jsonb_agg(x.league_name order by x.league_name) from (select distinct league_name from visible limit 200) x),'[]'::jsonb),
    'teams',coalesce((select jsonb_agg(x.name order by x.name) from (select home_team_name name from visible union select away_team_name from visible limit 1000) x),'[]'::jsonb)
  ) into result;
  return result;
end $function$
;

CREATE OR REPLACE FUNCTION public.search_footbazed(p_query text, p_limit integer DEFAULT 14)
 RETURNS TABLE(entity_type text, entity_id text, title text, subtitle text, meta text, relevance real)
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
  with input as (
    select replace(lower(btrim(coalesce(p_query, ''))),'ё','е') as query, least(greatest(coalesce(p_limit, 14), 1), 24) as result_limit
  ), club_results as (
    select distinct on (c.id) 'club'::text entity_type, c.id::text entity_id, c.name title,
      coalesce(nullif(c.area_name, ''), 'Клуб') subtitle, c.tla meta,
      greatest(case when lower(c.name)=i.query or replace(lower(ca.alias),'ё','е')=i.query then 1.0 when left(lower(c.name),char_length(i.query))=i.query then 0.96 when position(i.query in lower(c.name||' '||ca.alias))>0 then 0.88 else 0.0 end,
        extensions.similarity(lower(c.name||' '||ca.alias),i.query))::real relevance
    from public.clubs c left join public.club_aliases ca on ca.club_id=c.id cross join input i
    where char_length(i.query)>=2 and (position(i.query in lower(c.name||' '||replace(coalesce(ca.alias,''),'ё','е')))>0 or extensions.similarity(lower(c.name||' '||replace(coalesce(ca.alias,''),'ё','е')),i.query)>=0.2)
    order by c.id,relevance desc
  ), competition_results as (
    select 'competition'::text entity_type, cp.id::text entity_id, cp.name title,
      coalesce(nullif(cp.area_name,''),'Турнир') subtitle, cp.code meta,
      greatest(case when lower(cp.name)=i.query or lower(coalesce(cp.code,''))=i.query then 0.99 when left(lower(cp.name),char_length(i.query))=i.query then 0.94 when position(i.query in lower(cp.name||' '||coalesce(cp.code,'')||' '||case cp.code when 'CL' then 'лига чемпионов' when 'PL' then 'апл английская премьер-лига' when 'PD' then 'ла лига' when 'BL1' then 'бундеслига' when 'SA' then 'серия а' when 'FL1' then 'лига 1' when 'EL' then 'лига европы' else '' end))>0 then 0.86 else 0.0 end,
        extensions.similarity(lower(cp.name||' '||coalesce(cp.code,'')||' '||case cp.code when 'CL' then 'лига чемпионов' when 'PL' then 'апл английская премьер-лига' when 'PD' then 'ла лига' when 'BL1' then 'бундеслига' when 'SA' then 'серия а' when 'FL1' then 'лига 1' when 'EL' then 'лига европы' else '' end),i.query))::real relevance
    from public.competitions cp cross join input i
    where char_length(i.query)>=2 and (position(i.query in lower(cp.name||' '||coalesce(cp.code,'')||' '||case cp.code when 'CL' then 'лига чемпионов' when 'PL' then 'апл английская премьер-лига' when 'PD' then 'ла лига' when 'BL1' then 'бундеслига' when 'SA' then 'серия а' when 'FL1' then 'лига 1' when 'EL' then 'лига европы' else '' end))>0 or extensions.similarity(lower(cp.name||' '||coalesce(cp.code,'')||' '||case cp.code when 'CL' then 'лига чемпионов' when 'PL' then 'апл английская премьер-лига' when 'PD' then 'ла лига' when 'BL1' then 'бундеслига' when 'SA' then 'серия а' when 'FL1' then 'лига 1' when 'EL' then 'лига европы' else '' end),i.query)>=0.2)
  ), player_results as (
    select 'player'::text entity_type,p.id::text entity_id,p.name title,coalesce(c.short_name,c.name,p.team) subtitle,p.position meta,
      greatest(case when lower(p.name)=i.query then 1.0 when left(lower(p.name),char_length(i.query))=i.query then 0.95 when position(i.query in lower(p.name))>0 then 0.87 else 0.0 end,extensions.similarity(lower(p.name),i.query))::real relevance
    from public.players p left join public.clubs c on c.id=p.club_id cross join input i
    where char_length(i.query)>=2 and (position(i.query in lower(p.name))>0 or extensions.similarity(lower(p.name),i.query)>=0.28)
  ), match_results as (
    select 'match'::text entity_type,m.id::text entity_id,m.home_team_name||' — '||m.away_team_name title,m.league_name subtitle,m.status meta,
      greatest(case when (position(i.query in lower(m.home_team_name||' '||m.away_team_name||' '||m.league_name))>0 or exists(select 1 from public.club_aliases ca where ca.club_id in (m.home_club_id,m.away_club_id) and position(replace(lower(i.query),'ё','е') in replace(replace(lower(ca.alias),'ё','е'),'ё','е'))>0) or exists(select 1 from public.competitions cp where cp.id=m.competition_id and position(lower(i.query) in case cp.code when 'CL' then 'лига чемпионов' when 'PL' then 'апл английская премьер-лига' when 'PD' then 'ла лига' when 'BL1' then 'бундеслига' when 'SA' then 'серия а' when 'FL1' then 'лига 1' when 'EL' then 'лига европы' else '' end)>0)) then 0.82 else 0.0 end,extensions.similarity(lower(m.home_team_name||' '||m.away_team_name||' '||m.league_name),i.query))::real relevance
    from public.matches m cross join input i where char_length(i.query)>=2 and ((position(i.query in lower(m.home_team_name||' '||m.away_team_name||' '||m.league_name))>0 or exists(select 1 from public.club_aliases ca where ca.club_id in (m.home_club_id,m.away_club_id) and position(replace(lower(i.query),'ё','е') in replace(replace(lower(ca.alias),'ё','е'),'ё','е'))>0) or exists(select 1 from public.competitions cp where cp.id=m.competition_id and position(lower(i.query) in case cp.code when 'CL' then 'лига чемпионов' when 'PL' then 'апл английская премьер-лига' when 'PD' then 'ла лига' when 'BL1' then 'бундеслига' when 'SA' then 'серия а' when 'FL1' then 'лига 1' when 'EL' then 'лига европы' else '' end)>0)) or extensions.similarity(lower(m.home_team_name||' '||m.away_team_name||' '||m.league_name),i.query)>=0.2)
  ), user_results as (
    select 'user'::text entity_type,u.id::text entity_id,coalesce(nullif(u.display_name,''),u.username,'Пользователь') title,
      case when u.username is null then 'Профиль' else '@'||u.username end subtitle,'Профиль'::text meta,
      greatest(case when lower(coalesce(u.username,''))=i.query then 1.0 when left(lower(coalesce(u.username,'')),char_length(i.query))=i.query then 0.95 when position(i.query in lower(coalesce(u.display_name,'')||' '||coalesce(u.username,'')))>0 then 0.84 else 0.0 end,extensions.similarity(lower(coalesce(u.display_name,'')||' '||coalesce(u.username,'')),i.query))::real relevance
    from public.users u cross join input i where char_length(i.query)>=2 and (u.is_public=true or u.id=auth.uid()) and (position(i.query in lower(coalesce(u.display_name,'')||' '||coalesce(u.username,'')))>0 or extensions.similarity(lower(coalesce(u.display_name,'')||' '||coalesce(u.username,'')),i.query)>=0.25)
  ), combined as (
    select * from club_results union all select * from competition_results union all select * from player_results union all select * from match_results union all select * from user_results
  ), ranked as (
    select c.*,row_number() over(partition by c.entity_type order by c.relevance desc,c.title) type_position from combined c
  )
  select r.entity_type,r.entity_id,r.title,r.subtitle,r.meta,r.relevance from ranked r
  where r.type_position<=case r.entity_type when 'club' then 4 when 'competition' then 3 when 'player' then 4 when 'match' then 5 when 'user' then 3 else 2 end
  order by r.relevance desc,case r.entity_type when 'club' then 1 when 'competition' then 2 when 'player' then 3 when 'match' then 4 else 5 end,r.title
  limit(select result_limit from input);
$function$
;
