create extension if not exists pg_trgm with schema extensions;

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  league_name text not null,
  home_team_name text not null,
  away_team_name text not null,
  match_date timestamptz not null,
  status text default 'scheduled' check (status = any (array['scheduled', 'live', 'finished', 'postponed', 'cancelled'])),
  home_score smallint check (home_score is null or home_score >= 0),
  away_score smallint check (away_score is null or away_score >= 0),
  external_id bigint unique,
  league_code text,
  matchday integer,
  season text,
  api_fixture_id integer
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null,
  team text not null,
  position text,
  photo_url text,
  created_at timestamp default now(),
  shirt_number integer,
  unique (name, team)
);

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  email text,
  avatar_url text,
  bio text,
  favorite_teams text,
  invite_code text unique,
  ratings_count integer default 0,
  avg_rating numeric default 0,
  streak integer default 0,
  streak_date date,
  is_public boolean default true,
  created_at timestamptz default now(),
  last_seen timestamptz default now(),
  is_admin boolean not null default false
);

create table if not exists public.ratings (
  id integer generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  match_id bigint not null references public.matches(id) on delete cascade,
  match_rating smallint not null check (match_rating between 1 and 10),
  comment text,
  is_public boolean default true,
  created_at timestamptz default now(),
  unique (user_id, match_id)
);

create table if not exists public.player_ratings (
  id integer generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  match_id bigint not null references public.matches(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  rating smallint check (rating between 1 and 10),
  is_best_player boolean default false,
  unique (user_id, match_id, player_id)
);

create table if not exists public.predictions (
  id integer generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  match_id bigint not null references public.matches(id) on delete cascade,
  home_pred integer not null check (home_pred between 0 and 99),
  away_pred integer not null check (away_pred between 0 and 99),
  created_at timestamptz default now(),
  unique (user_id, match_id)
);

create table if not exists public.friendships (
  id integer generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  friend_id uuid not null references auth.users(id) on delete cascade,
  status text default 'pending' check (status = any (array['pending', 'accepted', 'rejected'])),
  created_at timestamptz default now(),
  check (user_id <> friend_id),
  unique (user_id, friend_id)
);

create table if not exists public.rating_likes (
  id integer generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  rating_id integer not null references public.ratings(id) on delete cascade,
  created_at timestamptz default now(),
  unique (user_id, rating_id)
);

create table if not exists public.notifications (
  id integer generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  from_user_id uuid references auth.users(id) on delete cascade,
  type text not null check (type = any (array['friend_request', 'like', 'comment', 'system'])),
  message text check (message is null or char_length(message) <= 500),
  read boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.chat_messages (
  id integer generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  message text not null check (char_length(message) between 1 and 1000),
  created_at timestamptz default now()
);

create table if not exists public.rating_comments (
  id integer generated by default as identity primary key,
  rating_id integer not null references public.ratings(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  comment text not null check (char_length(comment) between 1 and 2000),
  created_at timestamptz default now()
);

-- Retained only to reproduce the deployed schema. These legacy tables remain
-- inaccessible to API roles and are candidates for a later archival migration.
create table if not exists public.live_chat_messages (
  id bigint generated by default as identity primary key,
  match_id bigint not null,
  user_id bigint not null,
  username text not null,
  message text not null,
  created_at timestamp default now()
);

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  user_id bigint,
  message text not null,
  status text default 'open',
  created_at timestamp default now()
);

create table if not exists public.referee_ratings (
  id bigint generated by default as identity primary key,
  user_id bigint,
  match_id bigint,
  referee_name text,
  rating integer,
  created_at timestamp default now()
);

create index if not exists matches_status_date_idx on public.matches (status, match_date);
create index if not exists matches_league_date_idx on public.matches (league_name, match_date);
create index if not exists players_team_name_idx on public.players (team, name);
create index if not exists ratings_user_created_idx on public.ratings (user_id, created_at desc);
create index if not exists player_ratings_match_user_idx on public.player_ratings (match_id, user_id);
create index if not exists player_ratings_player_idx on public.player_ratings (player_id);
create index if not exists predictions_match_idx on public.predictions (match_id);
create index if not exists friendships_friend_status_idx on public.friendships (friend_id, status);
create index if not exists notifications_user_created_idx on public.notifications (user_id, created_at desc);
create index if not exists notifications_from_user_idx on public.notifications (from_user_id);
create index if not exists rating_likes_rating_idx on public.rating_likes (rating_id);
create index if not exists rating_comments_rating_created_idx on public.rating_comments (rating_id, created_at);
create index if not exists rating_comments_user_idx on public.rating_comments (user_id);
create index if not exists chat_messages_match_created_idx on public.chat_messages (match_id, created_at);
create index if not exists chat_messages_user_idx on public.chat_messages (user_id);

create or replace function public.normalize_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if (select auth.uid()) = new.id then
    new.email := null;
    new.ratings_count := 0;
    new.avg_rating := 0;
    new.streak := 0;
    new.streak_date := null;
    new.is_admin := false;
  end if;
  if new.invite_code is null or btrim(new.invite_code) = '' then
    loop
      new.invite_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
      exit when not exists (select 1 from public.users where invite_code = new.invite_code);
    end loop;
  end if;
  return new;
end
$function$;

create or replace function public.protect_user_profile_fields()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if (select auth.uid()) = old.id
    and current_setting('app.allow_managed_profile_update', true) is distinct from 'true'
    and (
      new.id is distinct from old.id or new.email is distinct from old.email
      or new.invite_code is distinct from old.invite_code
      or new.ratings_count is distinct from old.ratings_count
      or new.avg_rating is distinct from old.avg_rating
      or new.streak is distinct from old.streak
      or new.streak_date is distinct from old.streak_date
      or new.is_admin is distinct from old.is_admin
      or new.created_at is distinct from old.created_at
    )
  then
    raise exception 'This profile field is managed by FOOTBAZED.';
  end if;
  return new;
end
$function$;

create or replace function public.refresh_user_rating_stats()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  target_user uuid := coalesce(new.user_id, old.user_id);
begin
  perform set_config('app.allow_managed_profile_update', 'true', true);
  update public.users
  set ratings_count = (select count(*) from public.ratings where user_id = target_user),
      avg_rating = coalesce((select round(avg(match_rating)::numeric, 1) from public.ratings where user_id = target_user), 0)
  where id = target_user;
  return coalesce(new, old);
end
$function$;

create or replace function public.record_rating_streak()
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  current_user_id uuid := (select auth.uid());
  previous_day date;
begin
  if current_user_id is null then raise exception 'Authentication is required.'; end if;
  select u.streak_date into previous_day from public.users u where u.id = current_user_id for update;
  if previous_day = current_date then return; end if;
  perform set_config('app.allow_managed_profile_update', 'true', true);
  update public.users
  set streak = case when previous_day = current_date - 1 then coalesce(streak, 0) + 1 else 1 end,
      streak_date = current_date
  where id = current_user_id;
end
$function$;

create or replace function public.get_my_profile()
returns setof public.users
language sql
stable
security definer
set search_path = ''
as $function$
  select u.* from public.users u where u.id = (select auth.uid());
$function$;

create or replace function public.resolve_invite_code(lookup_code text)
returns table (
  id uuid, username text, display_name text, avatar_url text, bio text,
  favorite_teams text, ratings_count integer, avg_rating numeric, streak integer,
  is_public boolean
)
language sql
stable
security definer
set search_path = ''
as $function$
  select u.id, u.username, u.display_name, u.avatar_url, u.bio,
         u.favorite_teams, u.ratings_count, u.avg_rating, u.streak, u.is_public
  from public.users u
  where upper(u.invite_code) = upper(btrim(lookup_code))
    and u.id <> (select auth.uid())
  limit 1;
$function$;

drop trigger if exists normalize_new_user_profile_trigger on public.users;
create trigger normalize_new_user_profile_trigger before insert on public.users
for each row execute function public.normalize_new_user_profile();

drop trigger if exists protect_user_profile_fields_trigger on public.users;
create trigger protect_user_profile_fields_trigger before update on public.users
for each row execute function public.protect_user_profile_fields();

drop trigger if exists refresh_user_rating_stats_trigger on public.ratings;
create trigger refresh_user_rating_stats_trigger after insert or update or delete on public.ratings
for each row execute function public.refresh_user_rating_stats();

alter table public.matches enable row level security;
alter table public.players enable row level security;
alter table public.users enable row level security;
alter table public.ratings enable row level security;
alter table public.player_ratings enable row level security;
alter table public.predictions enable row level security;
alter table public.friendships enable row level security;
alter table public.rating_likes enable row level security;
alter table public.notifications enable row level security;
alter table public.chat_messages enable row level security;
alter table public.rating_comments enable row level security;
alter table public.referee_ratings enable row level security;

create policy "Public read matches" on public.matches for select to anon, authenticated using (true);
create policy "Public read players" on public.players for select to anon, authenticated using (true);
create policy "Public read users" on public.users for select to anon, authenticated using (is_public = true or id = (select auth.uid()));
create policy "Create own profile" on public.users for insert to authenticated with check ((select auth.uid()) = id);
create policy "Update own profile" on public.users for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy "Public read ratings" on public.ratings for select to anon, authenticated using (is_public = true or (select auth.uid()) = user_id);
create policy "Create own rating" on public.ratings for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Update own rating" on public.ratings for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Delete own rating" on public.ratings for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Read visible player ratings" on public.player_ratings for select to anon, authenticated using (
  (select auth.uid()) = user_id or exists (
    select 1 from public.ratings r
    where r.user_id = player_ratings.user_id and r.match_id = player_ratings.match_id and r.is_public = true
  )
);
create policy "Create own player rating" on public.player_ratings for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Update own player rating" on public.player_ratings for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Delete own player rating" on public.player_ratings for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Read own predictions" on public.predictions for select to authenticated using ((select auth.uid()) = user_id);
create policy "Create own prediction" on public.predictions for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Update own prediction" on public.predictions for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Delete own prediction" on public.predictions for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Read own friendships" on public.friendships for select to authenticated using ((select auth.uid()) in (user_id, friend_id));
create policy "Remove own friendship" on public.friendships for delete to authenticated using ((select auth.uid()) in (user_id, friend_id));

create policy "Read visible rating likes" on public.rating_likes for select to anon, authenticated using (
  exists (select 1 from public.ratings r where r.id = rating_likes.rating_id and (r.is_public = true or r.user_id = (select auth.uid())))
);
create policy "Create own rating like" on public.rating_likes for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Remove own rating like" on public.rating_likes for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Read own notifications" on public.notifications for select to authenticated using ((select auth.uid()) = user_id);
create policy "Mark own notification read" on public.notifications for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Create verified friend notification" on public.notifications for insert to authenticated with check ((select auth.uid()) = from_user_id);

create policy "Public read match chat" on public.chat_messages for select to anon, authenticated using (true);
create policy "Create own match chat message" on public.chat_messages for insert to authenticated with check ((select auth.uid()) = user_id);

create policy "Read visible rating comments" on public.rating_comments for select to anon, authenticated using (
  (select auth.uid()) = user_id or exists (
    select 1 from public.ratings r where r.id = rating_comments.rating_id and (r.is_public = true or r.user_id = (select auth.uid()))
  )
);
create policy "Create own rating comment" on public.rating_comments for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Edit own rating comment" on public.rating_comments for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Delete own rating comment" on public.rating_comments for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Public read referee ratings" on public.referee_ratings for select to anon, authenticated using (true);

notify pgrst, 'reload schema';
